/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void txtMsgReceive_Change(GTextArea source, GEvent event) { //_CODE_:txtMsgReceive:653858:
  println("textarea1 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:txtMsgReceive:653858:

public void btnSend_Click(GButton source, GEvent event) { //_CODE_:btnSend:500642:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write(txtSendMsg.getText());
  txtSendMsg.setText("");
} //_CODE_:btnSend:500642:

public void txtSendMsg_Change(GTextField source, GEvent event) { //_CODE_:txtSendMsg:568846:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
  
} //_CODE_:txtSendMsg:568846:

public void btnLeft_Click(GButton source, GEvent event) { //_CODE_:btnLeft:308221:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('A');
} //_CODE_:btnLeft:308221:

public void btnRight_Click(GButton source, GEvent event) { //_CODE_:btnRight:604378:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('D');
} //_CODE_:btnRight:604378:

public void btnForward_Click(GButton source, GEvent event) { //_CODE_:btnForward:348760:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
   myPort.write('W');
} //_CODE_:btnForward:348760:

public void btnBack_Click(GButton source, GEvent event) { //_CODE_:btnBack:984108:
  println("button5 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('S');
} //_CODE_:btnBack:984108:

public void btnStop_Click(GButton source, GEvent event) { //_CODE_:btnStop:492459:
  println("btnStop - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('F');
} //_CODE_:btnStop:492459:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  txtMsgReceive = new GTextArea(this, 237, 11, 198, 199, G4P.SCROLLBARS_BOTH | G4P.SCROLLBARS_AUTOHIDE);
  txtMsgReceive.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  txtMsgReceive.setOpaque(true);
  txtMsgReceive.addEventHandler(this, "txtMsgReceive_Change");
  btnSend = new GButton(this, 231, 278, 91, 60);
  btnSend.setTextAlign(GAlign.LEFT, GAlign.TOP);
  btnSend.setText("Send message to Zumo");
  btnSend.setTextBold();
  btnSend.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  btnSend.addEventHandler(this, "btnSend_Click");
  txtSendMsg = new GTextField(this, 51, 298, 160, 30, G4P.SCROLLBARS_NONE);
  txtSendMsg.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  txtSendMsg.setOpaque(true);
  txtSendMsg.addEventHandler(this, "txtSendMsg_Change");
  btnLeft = new GButton(this, 6, 154, 80, 30);
  btnLeft.setText("Left");
  btnLeft.setTextBold();
  btnLeft.addEventHandler(this, "btnLeft_Click");
  btnRight = new GButton(this, 134, 151, 80, 31);
  btnRight.setText("Right");
  btnRight.setTextBold();
  btnRight.addEventHandler(this, "btnRight_Click");
  btnForward = new GButton(this, 70, 101, 80, 30);
  btnForward.setText("Forward");
  btnForward.setTextBold();
  btnForward.addEventHandler(this, "btnForward_Click");
  btnBack = new GButton(this, 73, 202, 80, 30);
  btnBack.setText("Back");
  btnBack.setTextBold();
  btnBack.addEventHandler(this, "btnBack_Click");
  btnStop = new GButton(this, 68, 248, 80, 30);
  btnStop.setText("Stop");
  btnStop.addEventHandler(this, "btnStop_Click");
}

// Variable declarations 
// autogenerated do not edit
GTextArea txtMsgReceive; 
GButton btnSend; 
GTextField txtSendMsg; 
GButton btnLeft; 
GButton btnRight; 
GButton btnForward; 
GButton btnBack; 
GButton btnStop; 
